{{- if .Values.update.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-segment-update
spec:
  schedule: "@weekly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: updater
            image: alpine
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - "apk update && apk add wget && cd /segments4 && for f in *.rd5; do wget -N {{ .Values.update.url }}/$f; done"
            volumeMounts:
              - mountPath: /segments4
                name: segments
          {{- with .Values.brouter.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
{{ end }}
