apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-api
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}-api
        image: "{{ .Values.brouter.image.repository }}:{{ .Values.brouter.image.tag }}"
        imagePullPolicy: "{{ .Values.brouter.image.pullPolicy }}"
        resources:
          requests:
            memory: "128Mi"
        env:
          - name: CLASSPATH
            value: "/brouter.jar"
          - name: SEGMENTSPATH
            value: "/segments4"
          - name: PROFILESPATH
            value: "/profiles2"
          - name: CUSTOMPROFILESPATH
            value: "customprofiles"
        volumeMounts:
          - mountPath: "/segments4"
            name: segments
      {{- with .Values.brouter.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
