{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.issuer }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuer }}
{{ end }}
spec:
  ingressClassName: {{ .Values.ingress.ingress_class }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
{{- if .Values.brouter_web.enabled }}
          - pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-web-service
                port:
                  number: 80
            path: /
{{ end }}
          - pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api-service
                port:
                  number: 17777
            path: /brouter
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secret }}
{{ end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-react-ingress
  namespace: {{ .Release.Namespace }}
{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.issuer }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /
{{ end }}
spec:
  ingressClassName: {{ .Values.ingress.ingress_class }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
{{- if .Values.brouter_react.enabled }}
          - pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-react-service
                port:
                  number: 80
            path: /beta
{{ end }}
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secret }}
{{ end }}
{{ end }}
