apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-api
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - name: api
      protocol: TCP
      port: 17777
      targetPort: 17777
  type: ClusterIP
---
{{- if .Values.brouter_web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-web
spec:
  selector:
    app: {{ .Release.Name }}-web
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
{{ end }}
---
{{- if .Values.brouter_react.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-react-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-react
spec:
  selector:
    app: {{ .Release.Name }}-react
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
{{ end }}
