apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-web
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}-web
        image: "{{ .Values.brouter_web.image.repository }}:{{ .Values.brouter_web.image.tag }}"
        imagePullPolicy: "{{ .Values.brouter_web.image.pullPolicy }}"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 5
        volumeMounts:
        - name: brouter-web-config
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
        resources:
          requests:
            memory: "128Mi"
      volumes:
      - name: brouter-web-config
        configMap:
          name: {{ .Release.Name }}-web-config
