
ingress:
  enabled: true
  ingress_class: nginx-external
  host: brouter.kokev.de
  tls:
    enabled: true
    issuer: "kokev-issuer"
    secret: brouter-tls

update:
  url: http://brouter.de/brouter/segments4

brouter:
  image:
    repository: ghcr.io/koskev/brouter
    pullPolicy: IfNotPresent
    tag: "2024.03.06"
  volumes:
    - name: segments
      hostPath:
        path: /mnt/shared_data/k8s/brouter/segments4

brouter_web:
  image:
    repository: ghcr.io/koskev/brouter-web
    pullPolicy: IfNotPresent
    tag: "2024.03.06"






