ingress:
  enabled: true
  ingress_class: nginx
  host: brouter.example.com
  tls:
    enabled: true
    issuer: null
    secret: brouter-tls


brouter:
  enabled: true
  image:
    repository: ghcr.io/koskev/brouter
    pullPolicy: IfNotPresent
    tag: "2024.03.07"
  volumes: []
  updater:
    enabled: true
    url: http://brouter.de/brouter/segments4

brouter_web:
  enabled: true
  image:
    repository: ghcr.io/koskev/brouter-web
    pullPolicy: IfNotPresent
    tag: "2024.03.07"

brouter_react:
  enabled: true
  image:
    repository: ghcr.io/koskev/brouter-react
    pullPolicy: IfNotPresent
    tag: "2024.03.10"
