# Can be overwritten by each module
ingress:
  enabled: false
  ingress_class: nginx
  host: brouter.example.com
  path: /
  port: 80
  tls:
    enabled: true
    issuer: null
    secret: brouter-tls

brouter:
  enabled: false
  image:
    repository: ghcr.io/koskev/brouter
    pullPolicy: IfNotPresent
    tag: "2024.04.08"
  volumes: []
  updater:
    enabled: true
    url: http://brouter.de/brouter/segments4
  ingress:
    path: /brouter
    port: 17777

brouter_web:
  enabled: false
  image:
    repository: ghcr.io/koskev/brouter-web
    pullPolicy: IfNotPresent
    tag: "2024.04.08"
  ingress: {}

brouter_react:
  enabled: false
  image:
    repository: ghcr.io/koskev/brouter-react
    pullPolicy: IfNotPresent
    tag: "2024.04.12"
  ingress: {}
