ingress:
  enabled: true
  ingress_class: nginx
  host: brouter.example.com
  tls:
    enabled: true
    issuer: null
    secret: brouter-tls

update:
  url: http://brouter.de/brouter/segments4

brouter:
  image:
    repository: ghcr.io/koskev/brouter
    pullPolicy: IfNotPresent
    tag: "2024.03.06"
  volumes: []

brouter_web:
  image:
    repository: ghcr.io/koskev/brouter-web
    pullPolicy: IfNotPresent
    tag: "2024.03.06"
